### ISSUE TITLE
security: possible security issue when using pull_request_target

### ISSUE THREAD

**Issue by schalkneethling** [mechanical-ink/allo-allo#101]
In https://github.com/actions/first-interaction/issues/10#issuecomment-1278884148 @cicirello mentioned that I might be opening myself to [security issue](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)(s) by using `pull_request_target`. I need to read more and see if using `pull_request` with the current permissions still work.

Thanks again for the tip @cicirello 🎉

**Comment by cicirello** [comment]
You're welcome. Your usage of `pull_request_target` might be safe enough. It depends on the details. With that event, the workflow has repository write access as well as access to repository secrets. That link explains the issues well. Although it also implies that `pull_request_target` is needed for commenting. I'm reasonably sure I've been able to do that with `pull_request`. I'll try to track down which of my repos to verify.

**Comment by schalkneethling** [comment]
> You're welcome. Your usage of `pull_request_target` might be safe enough. It depends on the details. With that event, workflow runs from external forks have repository write access as well as access to repository secrets. That link explains the issues well. Although it also implies that `pull_request_target` is needed for commenting. I'm reasonably sure I've been able to do that with `pull_request`. I'll try to track down which of my repos to verify.

Thank you so much for the additional info, @cicirello 🙏
